### ISSUE TITLE
I. CA SecureStore kvalifikovaný certifikát nefunguje by default

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/autogram#273]
Pre podpis kvalifikovaným certifikátom z karty I. CA SecureStore Starcos 3.7 je potrebné zmeniť nastevenie cez obslužnú aplikáciu SecureStore. V nastaveniach v "PIN CACHE" záložke zaškrtnúť políčko "povolit PIN cache pro eSign" a uložiť.

Idk, či to vieme v Autograme nejakým spôsobom spraviť aj bez toho.

Bez tohto hodí Autogram takýto error:
```
	digital.slovensko.autogram.core.errors.UnrecognizedException: eu.europa.esig.dss.model.DSSException: Unable to sign : sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_NOT_LOGGED_IN
		at digital.slovensko.autogram.core.errors.AutogramException.createFromDSSException(AutogramException.java:56)
		at digital.slovensko.autogram.core.Autogram.lambda$10(Autogram.java:105)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: eu.europa.esig.dss.model.DSSException: Unable to sign : sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_NOT_LOGGED_IN
		at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:88)
		at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:66)
		at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:58)
		at digital.slovensko.autogram.core.SigningKey.sign(SigningKey.java:25)
		at digital.slovensko.autogram.core.SigningJob.signDocumentAsAsiCWithXAdeS(SigningJob.java:106)
		at digital.slovensko.autogram.core.SigningJob.signWithKeyAndRespond(SigningJob.java:61)
		at digital.slovensko.autogram.core.Autogram.lambda$10(Autogram.java:102)
		... 1 more
	Caused by: java.security.ProviderException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_NOT_LOGGED_IN
		at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:671)
		at java.base/java.security.Signature$Delegate.engineSign(Signature.java:1423)
		at java.base/java.security.Signature.sign(Signature.java:712)
		at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:142)
		at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:82)
		... 7 more
	Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_USER_NOT_LOGGED_IN
		at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_Sign(Native Method)
		at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.engineSign(P11Signature.java:650)
		... 11 more
```

**Comment by celuchmarek** [comment]
I.CA Securestore už (od verzie v2.1.2) funguje aj bez zmeny cache pin nastavenia v SecureStore appke, ale pýta to potom podpisový PIN, ktorý je treba zadať rovnaký ako user PIN. Nastavením v spomenutej appke sa tento krok ostráni.
