### ISSUE TITLE
nemoznost podpisovat - po aktualizacii na 2.0.1

### ISSUE THREAD

**Issue by nekromoff** [slovensko-digital/autogram#340]
```
Error:
digital.slovensko.autogram.core.errors.UnrecognizedException: eu.europa.esig.dss.model.DSSException: Unable to sign : Initialization failed
	at digital.slovensko.autogram.core.errors.AutogramException.createFromDSSException(AutogramException.java:56)
	at digital.slovensko.autogram.ui.gui.GUI.signBatch(GUI.java:91)
	at digital.slovensko.autogram.core.Autogram.lambda$batchSign$14(Autogram.java:156)
	at digital.slovensko.autogram.ui.gui.GUI.onWorkThreadDo(GUI.java:417)
	at digital.slovensko.autogram.core.Autogram.batchSign(Autogram.java:155)
	at digital.slovensko.autogram.ui.BatchGuiFileResponder.onBatchStartSuccess(BatchGuiFileResponder.java:63)
	at digital.slovensko.autogram.core.AutogramBatchStartCallback.handleSuccess(AutogramBatchStartCallback.java:42)
	at digital.slovensko.autogram.core.AutogramBatchStartCallback.accept(AutogramBatchStartCallback.java:24)
	at digital.slovensko.autogram.core.AutogramBatchStartCallback.accept(AutogramBatchStartCallback.java:9)
	at digital.slovensko.autogram.ui.gui.BatchDialogController.lambda$onMainButtonPressed$3(BatchDialogController.java:92)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: eu.europa.esig.dss.model.DSSException: Unable to sign : Initialization failed
	at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:88)
	at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:66)
	at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:58)
	at digital.slovensko.autogram.core.SigningKey.sign(SigningKey.java:25)
	at digital.slovensko.autogram.core.SigningJob.signDocumentAsPAdeS(SigningJob.java:137)
	at digital.slovensko.autogram.core.SigningJob.signWithKeyAndRespond(SigningJob.java:52)
	at digital.slovensko.autogram.ui.gui.GUI.signBatch(GUI.java:86)
	... 9 more
Caused by: java.security.ProviderException: Initialization failed
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.initialize(Unknown Source)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11Signature.engineInitSign(Unknown Source)
	at java.base/java.security.Signature$Delegate.engineInitSign(Unknown Source)
	at java.base/java.security.Signature.initSign(Unknown Source)
	at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:140)
	at eu.europa.esig.dss.token.AbstractSignatureTokenConnection.sign(AbstractSignatureTokenConnection.java:82)
	... 15 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_OPERATION_ACTIVE
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_SignInit(Native Method)
	... 21 more
```

**Comment by nekromoff** [comment]
aktualizoval som na 2.0.5, cize pasé
