### ISSUE TITLE
Chyba ASiC-E kontajnera - najdenych viacero dokumentov na podpis (v2.1.5)

### ISSUE THREAD

**Issue by mhudec** [slovensko-digital/autogram#401]
Pri asice subore zo zarucenej konverzie s osvedcovacou dolozkou Autogram (v2.1.5) zobrazuje chybu (ASiC-E kontajnera), ze bolo najdenych viacero dokumentov na podpis, hoci som chcel riesit iba overenie (mimochdoom, v cervenom nadpise je preklep "dokumnetov"), detail chyby je nizsie... po stlaceni Pokracovat sa nic neudeje, Autogram sa tvari, ze nic nenacital. Obsah asice suboru tvoria PDF a osvedcovacia dolozka, plus podpis s casovou peciatkou (pouzil som D.Viewer .NET).

```
digital.slovensko.autogram.core.errors.MultipleOriginalDocumentsFoundException
	at digital.slovensko.autogram.util.AsicContainerUtils.getOriginalDocument(AsicContainerUtils.java:41)
	at digital.slovensko.autogram.core.SigningParameters.buildParameters(SigningParameters.java:225)
	at digital.slovensko.autogram.core.SigningParameters.buildForASiCWithXAdES(SigningParameters.java:296)
	at digital.slovensko.autogram.core.SigningJob.getParametersForFile(SigningJob.java:213)
	at digital.slovensko.autogram.core.SigningJob.buildFromFile(SigningJob.java:184)
	at digital.slovensko.autogram.ui.gui.MainMenuController.signFiles(MainMenuController.java:113)
	at digital.slovensko.autogram.ui.gui.MainMenuController.onFilesSelected(MainMenuController.java:81)
	at digital.slovensko.autogram.ui.gui.MainMenuController.lambda$initialize$4(MainMenuController.java:51)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$DnDGesture.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$DnDGesture.processTargetDrop(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

s pozdravom,
 Martin Hudec

**Comment by celuchmarek** [comment]
Zdravím. Autogram zatiaľ nepodporuje podpisovanie ani overovanie viacerých súborov v asicu. To zahŕňa aj prípad zaručenej konverzie s autorizačnou doložkou. Chybová hláška, že bolo nájdených viacero dokumentov by mala používateľa informovať, že tento scenár Autogram nepodporuje a teda ten súbor ďalej nespracuje.

Ak je teda hláška málo výpovedná a nedozvedeli ste sa z nej, že Autogram so súborom zámerne nič ďalšie nespraví, stojí za prehodnotenie formulácia tohto upozornenia.

**Comment by mhudec** [comment]
Takze v buducnosti by takato podpora mohla vzniknut, prosim?

A ano, mozno by bolo dobre zvazit prepisanie tej chybovej hlasky...

1.) miesto nadpisu ```Chyba ASiC-E kontajnera``` dat napriklad ```Nepodporovana funkcia``` (nejde totiz o chybu kontajnera, ten je v poriadku, ide iba o nepodporovanu funkcionalitu)

2.) miesto cerveneho ```Najdenych viacero dokumnetov na podpis``` dat napriklad ```Najdenych viacero dokumentov na podpis alebo overenie.``` (tak ako je ponuknute aj v uvodnom okne, clovek moze chciet iba overenie, nemusi nutne potrebovat podpisovanie)

3.) miesto cierneho ```V kontajneri bolo najdenych viacero dokumentov na podpis``` dat napriklad ```V kontajneri bolo najdenych viacero dokumentov na podpis alebo overenie, tato funkcia zatial nie je podporovana.``` (v podstate suhrnne vysvetlenie/zhrnutie)

**Comment by celuchmarek** [comment]
Issue je nahradená novou plánovanou feature #429
