### ISSUE TITLE
Chyba Nezadali ste kod - bez vyziadania kodu (v2.1.5)

### ISSUE THREAD

**Issue by nekromoff** [slovensko-digital/autogram#415]
Podpisat - nic si nevyziada a vyhodi chybu

```
digital.slovensko.autogram.core.errors.FunctionCanceledException
	at digital.slovensko.autogram.core.errors.AutogramException.createFromDSSException(AutogramException.java:51)
	at digital.slovensko.autogram.core.Autogram.lambda$fetchKeysAndThen$24(Autogram.java:221)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by nekromoff** [comment]
Na druhykrat to uz zbehlo. Cize nejaky problem s delayom niekde v internals.

**Comment by celuchmarek** [comment]
@nekromoff Toto sa potom ešte opakovalo?

**Comment by nekromoff** [comment]
Zatial nie. Ale je fakt, ze som pouzil len parkrat odvtedy. Je to asi nejaka race condition.
