### ISSUE TITLE
Neočakávaná chyba: RuntimeException: error.launchFailed.header port is already in use

### ISSUE THREAD

**Issue by jozefizso** [slovensko-digital/autogram#481]
Pri podpisovaní PDF dokumentky na Elektronickej schránke Slovensko.sk sa spustí Autogram appka, ale komp začal zamŕzať, Autogram prestal odpovedať, až vyhodil chybu Neočakávaná chyba.

```
digital.slovensko.autogram.core.errors.UnrecognizedException: java.lang.RuntimeException: error.launchFailed.header port is already in use
	at digital.slovensko.autogram.ui.gui.GUIApp.lambda$start$1(GUIApp.java:65)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: error.launchFailed.header port is already in use
	at digital.slovensko.autogram.server.AutogramServer.buildServer(AutogramServer.java:92)
	at digital.slovensko.autogram.server.AutogramServer.<init>(AutogramServer.java:29)
	at digital.slovensko.autogram.ui.gui.GUIApp.start(GUIApp.java:38)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	... 7 more
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(Unknown Source)
	at digital.slovensko.autogram.server.AutogramServer.buildServer(AutogramServer.java:56)
	... 11 more
```

**Comment by celuchmarek** [comment]
Aký máš, prosím, operačný systém? Táto hláška inak znamená, že jeden Autogram už spustený je - treba ho zavrieť a skúsiť znova (prípadne, že nejaká iná aplikácia používa port 37200, čo je veľmi nepravdepodobné).

**Comment by jozefizso** [comment]
Používam Windows 10 Pro 22H2.

**Comment by celuchmarek** [comment]
K tomuto sme pridali custom error, keď je obsadený port. Zatiaľ to nerieši problém so zamŕzaním, ale skúsim cez víkend dokončiť #490 a bezprostredne po spustení appky, by sa mal komp už menej zapotiť.
