### ISSUE TITLE
Chyba: "The creation of new signatures is not permitted in the current document."

### ISSUE THREAD

**Issue by nekromoff** [slovensko-digital/autogram#495]
PDF asi bolo chranene heslom ci co (to vyhlasila ina podpisovacia aplikacia). Po Print to PDF podpisat kopiu ide.
Ale skor tu ide o UX, ked iba ouzivatel dostane genericku chybu - "nejde podpisat", bez uvedenia dovodu.

```
digital.slovensko.autogram.core.errors.UnrecognizedException: eu.europa.esig.dss.pades.exception.ProtectedDocumentException: The creation of new signatures is not permitted in the current document. Reason : PDF Permissions dictionary does not allow modification or creation interactive form fields, including signature fields when document is open with user-access!
	at digital.slovensko.autogram.core.errors.AutogramException.createFromDSSException(AutogramException.java:70)
	at digital.slovensko.autogram.core.Autogram.signCommonAndThen(Autogram.java:106)
	at digital.slovensko.autogram.core.Autogram.lambda$sign$13(Autogram.java:117)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: eu.europa.esig.dss.pades.exception.ProtectedDocumentException: The creation of new signatures is not permitted in the current document. Reason : PDF Permissions dictionary does not allow modification or creation interactive form fields, including signature fields when document is open with user-access!
	at eu.europa.esig.dss.pades.alerts.ProtectedDocumentExceptionOnStatusAlert$1.process(ProtectedDocumentExceptionOnStatusAlert.java:43)
	at eu.europa.esig.dss.pades.alerts.ProtectedDocumentExceptionOnStatusAlert$1.process(ProtectedDocumentExceptionOnStatusAlert.java:39)
	at eu.europa.esig.dss.alert.AbstractAlert.alert(AbstractAlert.java:62)
	at eu.europa.esig.dss.pdf.PdfPermissionsChecker.alertOnForbiddenSignatureCreation(PdfPermissionsChecker.java:153)
	at eu.europa.esig.dss.pdf.PdfPermissionsChecker.checkDocumentPermissions(PdfPermissionsChecker.java:90)
	at eu.europa.esig.dss.pdf.AbstractPDFSignatureService.checkPdfPermissions(AbstractPDFSignatureService.java:758)
	at eu.europa.esig.dss.pdf.pdfbox.PdfBoxSignatureService.computeDigest(PdfBoxSignatureService.java:138)
	at eu.europa.esig.dss.pdf.AbstractPDFSignatureService.messageDigest(AbstractPDFSignatureService.java:189)
	at eu.europa.esig.dss.pades.signature.PAdESService.computeDocumentDigest(PAdESService.java:195)
	at eu.europa.esig.dss.pades.signature.PAdESService.getDataToSign(PAdESService.java:182)
	at digital.slovensko.autogram.core.SigningJob.signDocumentAsPAdeS(SigningJob.java:150)
	at digital.slovensko.autogram.core.SigningJob.signWithKeyAndRespond(SigningJob.java:55)
	at digital.slovensko.autogram.core.Autogram.signCommonAndThen(Autogram.java:95)
	... 2 more
```

**Comment by celuchmarek** [comment]
Aha, ak je PDF chránené heslo, že sa bez hesla nedá ani zobraziť, to v Autograme vyhodí príslučnú chybovú hlášku. Toto je ale iný prípad - dokument je chránený heslo proti zmenám. Bude to treba ošetriť.

Vieš nám poradiť, kde si presne takéto PDF získal? Alebo to bola komerčná vec mimo verejných služieb?

**Comment by nekromoff** [comment]
Nebolo chranene heslom, ale nejako uzamknute. V kazdom pripade tlac do PDF z neho vytvorila odomknute PDF, cize zjavne to az taky problem nebol (aj ked rozumiem, ze tlac nie je v naplni Autogramu).

Nejaka zmluva, cize komercna vec.

**Comment by xhyrom** [comment]
Toto je ešte nejaký iný prípad ako hovorí @nekromoff. keďže pri pokuse podpísať PDF ktoré je chránené heslom a nedá sa bez neho ani zobraziť, dostaneme:
![image](https://github.com/user-attachments/assets/a762359e-e085-4c7a-a3af-393046ca909c)
![image](https://github.com/user-attachments/assets/f601ab6d-dda7-45a5-a0dc-a80d0d33650f)

presnejšie tu:
https://github.com/slovensko-digital/autogram/blob/82aa5ae4b35d5dc79f216f222352a2c091240fe6/src/main/java/digital/slovensko/autogram/ui/gui/MainMenuController.java#L62

mali by sme teda trochu lepšie ošetriť tieto chyby s uzamknutými PDF-kami.
