### ISSUE TITLE
Neznáma chyba pri otváraní 2 x ASICE (cez file association) v Autograme

### ISSUE THREAD

**Issue by nekromoff** [slovensko-digital/autogram#500]
v2.2.3, Linux, 2 ks ASICE -> otvoriť v Autogram

```
digital.slovensko.autogram.core.errors.UnrecognizedException: java.lang.RuntimeException: error.launchFailed.header port is already in use
	at digital.slovensko.autogram.ui.gui.GUIApp.lambda$start$1(GUIApp.java:65)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: error.launchFailed.header port is already in use
	at digital.slovensko.autogram.server.AutogramServer.buildServer(AutogramServer.java:92)
	at digital.slovensko.autogram.server.AutogramServer.<init>(AutogramServer.java:29)
	at digital.slovensko.autogram.ui.gui.GUIApp.start(GUIApp.java:38)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	... 7 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(Unknown Source)
	at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(Unknown Source)
	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(Unknown Source)
	at digital.slovensko.autogram.server.AutogramServer.buildServer(AutogramServer.java:56)
	... 11 more
```

**Comment by jsuchal** [comment]
@celuchmarek nejako otvarame automaticky subory s .asice priponou? lebo to by davalo zmysel

**Comment by celuchmarek** [comment]
Hej, to je veľmi logický scenár. Zatiaľ to nemáme, ale máme v backlogu (tuším ale, že to per platforma bude treba nastaviť).

Čo sa týka samotnej issue, ide zjavne o upravenú experimentálnu feature, takže je očakávané, že zatiaľ nefunguje podľa očakávania 😁

**Comment by nekromoff** [comment]
Očakával by som:
1. zrozumiteľnú info, napr.: "ASICE zatiaľ nevieme otvoriť. Podpisy si môžete overiť na: xxxxYYY"
2. keď už to bude implementované, tak okno s overením podpisov - podobne ako to robí Podpisuj, ktoré ASICE otvorí a zobrazí overenie

Nateraz teda viem, že podpisy musím overovať inde.

**Comment by celuchmarek** [comment]
@nekromoff otváranie, overovanie a podpisovanie asicov, samozrejme, funguje (zatiaľ s práve jedným dokumentom vo vnútri). Súbory ale treba otvoriť z Autogramu, teda otvoriť appku a cez ňu potom vybrať súbor.

Ty ale spomínaš, že si otvoril súbory cez file association, čo by ale nemalo ani fungovať 🤔 ten error v podstate hovorí, že sa Autogram chcel spustiť viackrát naraz. Tie associations "otvoriť v Autograme" sme zatiaľ neriešili.

Ako sa ti vlastne k "otvoriť v Autograme" podarilo dostať? Upravoval si manuálne nejaký config?

**Comment by nekromoff** [comment]
OK, rozumiem. 

Nie, nič špeciálne - pravý klik, otvoriť v ..., vybrať Autogram. To je celé.

**Comment by nekromoff** [comment]
Takze sa to deje, aj pri otvoreni 1 suboru zo systemu. Malo by sa to spravat rovnako ako pri otvoreni cez Vyberte subor.
